import type { AnalysisResult, InterviewResult } from '../types/index.js';
import { logger } from '../utils/logger.js';
import { confirm } from '../utils/prompt.js';

export async function interview(
  analysis: AnalysisResult,
  options: { auto: boolean },
): Promise<InterviewResult> {
  if (options.auto) {
    return autoInterview(analysis);
  }
  return interactiveInterview(analysis);
}

function autoInterview(analysis: AnalysisResult): InterviewResult {
  logger.info('Auto mode: generating optimal setup based on analysis...');

  const hasWebProject = analysis.stack.frameworks.some((f) =>
    ['React', 'Vue', 'Next.js', 'Nuxt', 'Svelte', 'Angular'].includes(f),
  );

  return {
    setupDomains: {
      claudeEnv: true,
      processDocs: true,
      cicd: analysis.git.isRepo,
    },
    tools: {
      omc: true,
      openspec: true,
      exaAi: false,
      perplexityAsk: false,
      githubMcp: analysis.git.remoteUrl?.includes('github.com') ?? false,
      context7: analysis.stack.languages.length > 0,
      harness: hasWebProject || analysis.structure.hasMonorepo,
    },
    preferences: {
      autoGenerated: true,
      stack: analysis.stack,
    },
  };
}

async function interactiveInterview(analysis: AnalysisResult): Promise<InterviewResult> {
  logger.blank();
  logger.info('Setting up vibe coding environment. Answering a few questions...');
  logger.blank();

  const processDocs = await confirm('Set up vibe coding 5-stage process templates?');
  const cicd = analysis.git.isRepo
    ? await confirm('Set up CI/CD pipeline (pre-commit hooks + GitHub Actions)?')
    : false;

  logger.blank();
  logger.info('Select optional tools to install:');
  logger.blank();

  const openspec = await confirm('  OpenSpec (process documentation framework)?');
  const exaAi = await confirm('  Exa.ai MCP (code/technical doc search)?');
  const perplexityAsk = await confirm('  Perplexity MCP (general web search)?');
  const githubMcp = analysis.git.remoteUrl?.includes('github.com')
    ? await confirm('  GitHub MCP (issue/PR management)?')
    : false;
  const context7 = await confirm('  Context7 MCP (up-to-date library docs)?');
  const harness = await confirm('  Harness (domain-specific agent team design)?');

  return {
    setupDomains: {
      claudeEnv: true,
      processDocs,
      cicd,
    },
    tools: {
      omc: true,
      openspec,
      exaAi,
      perplexityAsk,
      githubMcp,
      context7,
      harness,
    },
    preferences: {},
  };
}
