import type { AnalysisResult, InterviewResult, ToolSelection } from '../types/index.js';
import { logger } from '../utils/logger.js';
import { confirm } from '../utils/prompt.js';

export async function interview(
  analysis: AnalysisResult,
  options: { auto: boolean },
): Promise<InterviewResult> {
  if (options.auto) {
    return autoInterview(analysis);
  }

  // Try AI-powered interview first, fall back to interactive
  try {
    return await aiInterview(analysis);
  } catch {
    logger.warn('AI interview unavailable. Falling back to manual mode.');
    return interactiveInterview(analysis);
  }
}

function autoInterview(analysis: AnalysisResult): InterviewResult {
  logger.info('Auto mode: generating optimal setup based on analysis...');

  const hasWebProject = analysis.stack.frameworks.some((f) =>
    ['React', 'Vue', 'Next.js', 'Nuxt', 'Svelte', 'Angular'].includes(f),
  );

  return {
    setupDomains: {
      claudeEnv: true,
      processDocs: true,
      cicd: analysis.git.isRepo,
    },
    tools: {
      omc: true,
      openspec: true,
      exaAi: false,
      perplexityAsk: false,
      githubMcp: analysis.git.remoteUrl?.includes('github.com') ?? false,
      context7: analysis.stack.languages.length > 0,
      harness: hasWebProject || analysis.structure.hasMonorepo,
      toolbox: true,
    },
    preferences: {
      autoGenerated: true,
      stack: analysis.stack,
    },
  };
}

async function aiInterview(analysis: AnalysisResult): Promise<InterviewResult> {
  const { query } = await import('@anthropic-ai/claude-agent-sdk');

  const systemPrompt = buildInterviewPrompt(analysis);

  logger.blank();
  logger.info('Starting AI-powered setup interview...');
  logger.blank();

  let resultJson = '';

  for await (const message of query({
    prompt: systemPrompt,
    options: {
      maxTurns: 10,
      systemPrompt: `You are ROBOCO, an AI assistant that helps set up vibe coding environments.
Analyze the repository information provided and ask the user targeted questions to determine the optimal setup.
After gathering enough information, output a JSON block with your recommendations.

IMPORTANT: When you have enough information, output your final recommendation as a JSON code block:
\`\`\`json
{
  "setupDomains": { "claudeEnv": true, "processDocs": boolean, "cicd": boolean },
  "tools": { "omc": true, "openspec": boolean, "exaAi": boolean, "perplexityAsk": boolean, "githubMcp": boolean, "context7": boolean, "harness": boolean, "toolbox": boolean },
  "preferences": {}
}
\`\`\``,
      allowedTools: [],
      permissionMode: 'plan',
    },
  })) {
    if ('result' in message) {
      resultJson = message.result;
    }
  }

  return parseAiResult(resultJson, analysis);
}

function buildInterviewPrompt(analysis: AnalysisResult): string {
  const parts = [
    `I want to set up a vibe coding environment for my repository.`,
    ``,
    `Repository analysis:`,
    `- Path: ${analysis.path}`,
    `- Languages: ${analysis.stack.languages.join(', ') || 'None detected'}`,
    `- Frameworks: ${analysis.stack.frameworks.join(', ') || 'None'}`,
    `- Package manager: ${analysis.stack.packageManager ?? 'None'}`,
    `- TypeScript: ${analysis.stack.hasTypeScript ? 'Yes' : 'No'}`,
    `- Git: ${analysis.git.isRepo ? `Yes (${analysis.git.repoName ?? 'local'})` : 'No'}`,
    `- Remote: ${analysis.git.remoteUrl ?? 'None'}`,
    `- Monorepo: ${analysis.structure.hasMonorepo ? 'Yes' : 'No'}`,
    `- Existing CLAUDE.md: ${analysis.existing.hasClaudeMd ? 'Yes' : 'No'}`,
    `- Existing .claude/: ${analysis.existing.hasClaude ? 'Yes' : 'No'}`,
    `- Existing .claude/skills: ${analysis.existing.claudeSkills.length > 0 ? analysis.existing.claudeSkills.join(', ') : 'None'}`,
    `- Existing .claude/commands: ${analysis.existing.claudeCommands.length > 0 ? analysis.existing.claudeCommands.join(', ') : 'None'}`,
    `- Existing settings.json: ${analysis.existing.claudeSettings ? 'Yes (will be merged)' : 'No'}`,
    `- Global ~/.claude/skills: ${analysis.existing.globalSkills.length > 0 ? analysis.existing.globalSkills.join(', ') : 'None'}`,
    ``,
    `Please ask me a few questions to determine the best setup, then provide your recommendation as JSON.`,
  ];
  return parts.join('\n');
}

function parseAiResult(result: string, analysis: AnalysisResult): InterviewResult {
  // Extract JSON from markdown code block
  const jsonMatch = result.match(/```json\s*([\s\S]*?)```/);
  if (jsonMatch?.[1]) {
    try {
      const parsed = JSON.parse(jsonMatch[1]) as {
        setupDomains?: { claudeEnv?: boolean; processDocs?: boolean; cicd?: boolean };
        tools?: Partial<ToolSelection>;
        preferences?: Record<string, unknown>;
      };
      return {
        setupDomains: {
          claudeEnv: true,
          processDocs: parsed.setupDomains?.processDocs ?? true,
          cicd: parsed.setupDomains?.cicd ?? analysis.git.isRepo,
        },
        tools: {
          omc: true,
          openspec: parsed.tools?.openspec ?? false,
          exaAi: parsed.tools?.exaAi ?? false,
          perplexityAsk: parsed.tools?.perplexityAsk ?? false,
          githubMcp: parsed.tools?.githubMcp ?? false,
          context7: parsed.tools?.context7 ?? false,
          harness: parsed.tools?.harness ?? false,
          toolbox: parsed.tools?.toolbox ?? true,
        },
        preferences: parsed.preferences ?? { aiGenerated: true },
      };
    } catch {
      // Fall through to auto
    }
  }

  // If AI result can't be parsed, fall back to auto
  logger.warn('Could not parse AI recommendation. Using auto-generated setup.');
  return autoInterview(analysis);
}

async function interactiveInterview(analysis: AnalysisResult): Promise<InterviewResult> {
  logger.blank();
  logger.info('Setting up vibe coding environment. Answering a few questions...');
  logger.blank();

  const processDocs = await confirm('Set up vibe coding 5-stage process templates?');
  const cicd = analysis.git.isRepo
    ? await confirm('Set up CI/CD pipeline (pre-commit hooks + GitHub Actions)?')
    : false;

  logger.blank();
  logger.info('Select optional tools to install:');
  logger.blank();

  const openspec = await confirm('  OpenSpec (process documentation framework)?');
  const exaAi = await confirm('  Exa.ai MCP (code/technical doc search)?');
  const perplexityAsk = await confirm('  Perplexity MCP (general web search)?');
  const githubMcp = analysis.git.remoteUrl?.includes('github.com')
    ? await confirm('  GitHub MCP (issue/PR management)?')
    : false;
  const context7 = await confirm('  Context7 MCP (up-to-date library docs)?');
  const harness = await confirm('  Harness (domain-specific agent team design)?');

  const overlayHints: string[] = [];
  if (analysis.stack.languages.includes('Go')) overlayHints.push('go-dev');
  if (
    analysis.stack.languages.includes('TypeScript') ||
    analysis.stack.languages.includes('JavaScript')
  ) {
    overlayHints.push('biome-vcs-integration');
  }
  if (analysis.signals.hasProto) overlayHints.push('protobuf-dev');
  const overlayMsg = overlayHints.length > 0 ? ` (also: ${overlayHints.join(', ')})` : '';
  const toolbox = await confirm(
    `  claude-toolbox bundle${overlayMsg} (next-action, todo, gh-issue-resolver, semgrep-review, sandbox-helpers, makefile-workflow)?`,
  );

  return {
    setupDomains: {
      claudeEnv: true,
      processDocs,
      cicd,
    },
    tools: {
      omc: true,
      openspec,
      exaAi,
      perplexityAsk,
      githubMcp,
      context7,
      harness,
      toolbox,
    },
    preferences: {},
  };
}
