import { describe, it, expect } from 'vitest';
import { interview } from '../../src/core/interviewer.js';
import type { AnalysisResult } from '../../src/types/index.js';

function makeAnalysis(): AnalysisResult {
  return {
    path: '/tmp/test',
    stack: {
      languages: ['TypeScript'],
      frameworks: ['React'],
      buildTools: [],
      packageManager: 'npm',
      hasTypeScript: true,
    },
    structure: { rootFiles: [], rootDirs: [], sourceDir: 'src', testDir: null, hasMonorepo: false },
    existing: {
      hasClaude: false,
      hasClaudeMd: false,
      hasOmc: false,
      hasRoboco: false,
      hasOpenSpec: false,
    },
    git: {
      isRepo: true,
      remoteUrl: 'https://github.com/test/repo.git',
      repoName: 'repo',
      branch: 'main',
    },
  };
}

describe('interviewer - auto mode', () => {
  it('returns valid InterviewResult with omc always true', async () => {
    const result = await interview(makeAnalysis(), { auto: true });
    expect(result.tools.omc).toBe(true);
    expect(result.setupDomains.claudeEnv).toBe(true);
  });

  it('enables processDocs and cicd in auto mode', async () => {
    const result = await interview(makeAnalysis(), { auto: true });
    expect(result.setupDomains.processDocs).toBe(true);
    expect(result.setupDomains.cicd).toBe(true);
  });

  it('enables github MCP when remote is github.com', async () => {
    const result = await interview(makeAnalysis(), { auto: true });
    expect(result.tools.githubMcp).toBe(true);
  });

  it('enables context7 when languages detected', async () => {
    const result = await interview(makeAnalysis(), { auto: true });
    expect(result.tools.context7).toBe(true);
  });

  it('enables harness for React projects', async () => {
    const result = await interview(makeAnalysis(), { auto: true });
    expect(result.tools.harness).toBe(true);
  });

  it('disables harness for non-web projects', async () => {
    const analysis = makeAnalysis();
    analysis.stack.frameworks = [];
    analysis.structure.hasMonorepo = false;
    const result = await interview(analysis, { auto: true });
    expect(result.tools.harness).toBe(false);
  });

  it('marks result as autoGenerated', async () => {
    const result = await interview(makeAnalysis(), { auto: true });
    expect(result.preferences).toHaveProperty('autoGenerated', true);
  });
});
